### ISSUE TITLE
Does it work on raspberry pi2?

### ISSUE THREAD

**Issue by Loongle** [mohaseeb/raspberrypi3-opencv-docker#6]
I tried to compile on pi2, but there was an exception.
I'm using version 4.1.0

![image](https://user-images.githubusercontent.com/7290992/58846939-9d6dd680-86b3-11e9-80e7-6ae237534c64.png)

**Comment by mohaseeb** [comment]
Hi,
I didn't try it on pi2. But check the following link
https://www.learnopencv.com/install-opencv-4-on-raspberry-pi/
